{% set name = "colour" %}
{% set version = "0.1.5" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "af20120fefd2afede8b001fbef2ea9da70ad7d49fafdb6489025dae8745c3aee" %}
{% set build = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python >=3.8
    - setuptools <=67  # deprecated setup.py install is used
    - d2to1

  run:
    - python >=3.8

test:
  imports:
    - colour

about:
  home: https://github.com/vaab/colour
  summary: 'Python color representations manipulation library (RGB, HSL, web, ...)'
  license_file: LICENSE
  license: BSD-2-Clause
  license_family: BSD
  dev_url: https://github.com/vaab/colour
  doc_url: https://github.com/vaab/colour

extra:
  recipe-maintainers:
    - fhoehle
    - pmlandwehr
